sudo: false
cache: pip

language: python

python:
    - 3.6
    - 2.7

env:
    TOXENV=py
    TOXENV=docs
    TOXENV=manifest

matrix:
    exclude:
        - python: 2.7
          env: TOXENV=manifest

install:
    - pip install tox

script:
    - tox
