parentcode = ('clv', 'deg', 'gly', 'lip', 'met', 'rib', 'sec', 'trt', 'upt')

typename = (
    'abundance',
    'acetylation',
    'activity',
    'acylation',
    'ADP-ribosylation',
    'alkylation',
    'amination',
    'binding',
    'carbamoylation',
    'carboxylation',
    'chemical synthesis',
    'cleavage',
    'cotreatment',
    'degradation',
    'ethylation',
    'export',
    'expression',
    'farnesylation',
    'folding',
    'geranoylation',
    'glucuronidation',
    'glutathionylation',
    'glycation',
    'glycosylation',
    'hydrolysis',
    'hydroxylation',
    'import',
    'lipidation',
    'localization',
    'metabolic processing',
    'methylation',
    'mutagenesis',
    'myristoylation',
    'N-linked glycosylation',
    'nitrosation',
    'nucleotidylation',
    'O-linked glycosylation',
    'oxidation',
    'palmitoylation',
    'phosphorylation',
    'prenylation',
    'reaction',
    'reduction',
    'response to substance',
    'ribosylation',
    'secretion',
    'splicing',
    'stability',
    'sulfation',
    'sumoylation',
    'transport',
    'ubiquitination',
    'uptake'
)

code = (
    'abu',
    'ace',
    'act',
    'acy',
    'alk',
    'ami',
    'arb',
    'b',
    'car',
    'clv',
    'cox',
    'csy',
    'deg',
    'eth',
    'exp',
    'ext',
    'far',
    'fol',
    'ger',
    'glc',
    'glt',
    'gly',
    'gyc',
    'hdx',
    'hyd',
    'imt',
    'lip',
    'loc',
    'met',
    'mut',
    'myl',
    'myr',
    'ngl',
    'nit',
    'nuc',
    'ogl',
    'oxd',
    'pal',
    'pho',
    'pre',
    'rec',
    'red',
    'rib',
    'rxn',
    'sec',
    'spl',
    'sta',
    'sul',
    'sum',
    'trt',
    'ubq',
    'upt',
    'w'
)

